// <auto-generated />
using System;
using BlackjackStreakSimulator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackjackStreakSimulator.Data.Migrations
{
    [DbContext(typeof(BlackjackStreakSimulatorDbContext))]
    [Migration("20260904025259_RenameTablesToSingular")]
    partial class RenameTablesToSingular
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlackjackStreakSimulator.Data.BatchHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageHandsPlayedWhenBusted")
                        .HasColumnType("float");

                    b.Property<double>("AverageHandsPlayedWhenReachedGoal")
                        .HasColumnType("float");

                    b.Property<decimal>("AverageMaxDrawdownWhenReachedGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankrollGoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BettingMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecksInShoe")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialBankroll")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxStreakCount")
                        .HasColumnType("int");

                    b.Property<int>("RunCount")
                        .HasColumnType("int");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("TimesBusted")
                        .HasColumnType("int");

                    b.Property<int>("TimesReachedGoal")
                        .HasColumnType("int");

                    b.Property<decimal>("WorstMaxDrawdownWhenReachedGoal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BatchHistoryEntry", (string)null);
                });

            modelBuilder.Entity("BlackjackStreakSimulator.Data.LowestBankrollBucketEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchHistoryEntryId")
                        .HasColumnType("int");

                    b.Property<int>("BucketFloor")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchHistoryEntryId");

                    b.ToTable("LowestBankrollBucketEntry", (string)null);
                });

            modelBuilder.Entity("BlackjackStreakSimulator.Data.StreakLengthFrequencyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchHistoryEntryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("StreakLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchHistoryEntryId");

                    b.ToTable("StreakLengthFrequencyEntry", (string)null);
                });

            modelBuilder.Entity("BlackjackStreakSimulator.Data.LowestBankrollBucketEntry", b =>
                {
                    b.HasOne("BlackjackStreakSimulator.Data.BatchHistoryEntry", null)
                        .WithMany("LowestBankrollBuckets")
                        .HasForeignKey("BatchHistoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlackjackStreakSimulator.Data.StreakLengthFrequencyEntry", b =>
                {
                    b.HasOne("BlackjackStreakSimulator.Data.BatchHistoryEntry", null)
                        .WithMany("StreakLengthFrequencies")
                        .HasForeignKey("BatchHistoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlackjackStreakSimulator.Data.BatchHistoryEntry", b =>
                {
                    b.Navigation("LowestBankrollBuckets");

                    b.Navigation("StreakLengthFrequencies");
                });
#pragma warning restore 612, 618
        }
    }
}
